In [1]:
import numpy as np

#### Print the numpy version and the configuration.

In [3]:
print(np.__version__)
np.__config__.show()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/tripvin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/tripvin/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/tripvin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/tripvin/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/tripvin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/tripvin/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/tripvin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/tripvin/Anaconda3\\Library\\include']


#### Create a null vector of size 10

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create a null vector of size 10 but the fifth value which is 1

In [6]:
Z = np.zeros(10)
Z[4]=1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Create a vector with values ranging from 10 to 99

In [8]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)


#### Declare a 3x3 identity matrix

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Declare a 5x5 matrix with values 1,2,3,4 just below the diagonal

Extract a diagonal or construct a diagonal array.

In [20]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Declare a 10x10x10 array with random values

In [22]:
np.random.random((10,10,10))

array([[[3.42268913e-02, 9.06787416e-01, 7.17488828e-01, 3.83487932e-01,
         5.26261127e-01, 5.76293844e-01, 4.61434139e-01, 8.31444859e-01,
         6.37342995e-01, 9.92600927e-01],
        [1.39696219e-01, 3.44318868e-01, 5.22413571e-01, 4.34126188e-01,
         3.94382118e-01, 3.54750433e-01, 5.73650055e-02, 2.80942901e-01,
         9.31385391e-01, 8.89963842e-01],
        [8.27436136e-01, 3.59142794e-02, 7.38620661e-01, 3.79647299e-01,
         7.73669512e-01, 8.08043741e-02, 6.92739055e-01, 8.75787977e-02,
         4.88053433e-01, 2.68807882e-01],
        [8.11183008e-01, 4.97986532e-02, 7.69546896e-01, 4.62469283e-01,
         2.70097036e-01, 6.68531828e-01, 1.44058777e-01, 1.82807826e-01,
         3.65629444e-01, 4.89401880e-01],
        [2.73891652e-01, 6.78362455e-01, 4.41551983e-01, 2.81997367e-01,
         5.09862259e-01, 9.01714090e-01, 1.06174607e-02, 8.57128273e-02,
         3.40042903e-01, 6.18724238e-01],
        [1.87197939e-01, 4.65435915e-01, 8.35061602e-01, 7.5