In [2]:
import numpy as np

#### Declare a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### Declare a 10x10 array with random values and find the minimum and maximum values

In [12]:
Z = np.random.random((10,10))
print(Z.min())
print(Z.max())

0.021358221943246436
0.9659928977485794


In [13]:
Z

array([[0.42429893, 0.30715969, 0.57749401, 0.8088798 , 0.70010112,
        0.79110909, 0.83955577, 0.72192675, 0.96137201, 0.800876  ],
       [0.87590008, 0.78814302, 0.54587815, 0.81982173, 0.43787686,
        0.78503807, 0.48343376, 0.54600013, 0.54158732, 0.06353732],
       [0.91921217, 0.18068421, 0.68354775, 0.37376972, 0.6031651 ,
        0.16057467, 0.3440539 , 0.49175094, 0.25539959, 0.21627529],
       [0.73727541, 0.09115232, 0.45170259, 0.16169076, 0.54108899,
        0.40817132, 0.13816389, 0.79318379, 0.78473243, 0.69923924],
       [0.18516803, 0.51378046, 0.93696687, 0.21975175, 0.53318649,
        0.40660409, 0.45097709, 0.59649186, 0.46550816, 0.55239472],
       [0.38549822, 0.80308514, 0.78768405, 0.90642538, 0.94218502,
        0.04519029, 0.65310776, 0.25448806, 0.02135822, 0.7248991 ],
       [0.35677276, 0.06181944, 0.16346986, 0.38221902, 0.43970558,
        0.41638628, 0.36886312, 0.41547382, 0.12928302, 0.50751605],
       [0.44142122, 0.81996412, 0.0476684

#### Create a checkerboard 8x8 matrix using the tile function

In [28]:
Z = np.tile([[0,1],[1,0]],(4,4))

In [29]:
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### Normalize a 5x5 random matrix (between 0 and 1)

In [33]:
Z = np.random.random((5,5))
Zmin = Z.min()
Zmax = Z.max()
Z = (Z-Zmin)/(Zmax-Zmin)
Z

array([[0.19091939, 1.        , 0.28564048, 0.37045673, 0.92122184],
       [0.63937895, 0.59872386, 0.01594625, 0.42298152, 0.23519683],
       [0.35811171, 0.90174817, 0.80593107, 0.27802266, 0.07810214],
       [0.02292353, 0.9179186 , 0.08047466, 0.40291183, 0.55093731],
       [0.69596506, 0.        , 0.36173422, 0.33562316, 0.35863576]])

#### Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [37]:
np.dot(np.random.randint(100,size=(5,3)),np.random.randint(200,size=(3,2)))

array([[11097, 12606],
       [ 6480,  4796],
       [16488, 13288],
       [14280, 10672],
       [15483,  9618]])

#### Create a 10x10 matrix with row values ranging from 0 to 9

In [40]:
Z = np.zeros((10,10))+np.arange(0,10)

In [41]:
Z

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

#### Create a random vector of size 100 and sort it

In [44]:
Z =np.random.random(100)
Z.sort()
# print(Z)

#### Consider two random matrices A anb B, check if they are equal.

In [48]:
a = np.random.randint(0,3,(3,4))
b = np.random.randint(2,4,(3,4))
np.allclose(a,b)

False

#### Create a random vector of size 1000 and find the mean value

In [53]:
Z = np.random.random(1000)
Z.mean()

0.508324767749841